name: Bot scan
on:
  pull_request:
    types: [ opened, reopened ]
permissions:
  issues: write
  pull-requests: write

jobs:
  Snyk_scanning:
    permissions: write-all
    name: Snyk Bot scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Snyk Bot scan
        continue-on-error: true
        run: |
         echo "----------Download Latest Snyk CLI-----------"
             npm i -g snyk@latest
             snyk --version
             npm install --legacy-peer-deps
             echo "----------Authenticating Snyk-----------"
             snyk auth ${{ secrets.SNYK_TOKEN }}
             echo "----------Snyk Yarn Scanning-----------"
             snyk test --yarn-workspaces --detection-depth=6 -d
             echo "----------Snyk Scanning-----------"
             snyk test --all-projects  -d
             snyk test --file=build.gradle --all-sub-projects -d
            
  TruffleHog_scanning:
    permissions: write-all
    name: TruffleHog Bot scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch all history so multiple commits can be scanned
      - name: TruffleHog Bot scan
        continue-on-error: true
        uses: trufflesecurity/TruffleHog-Enterprise-Github-Action@main
        with:
            args: ${{ github.event.repository.default_branch }} HEAD --fail-verified
  # security:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@master
  #     - name: Run Snyk to check for vulnerabilities
  #       uses: snyk/actions/node@master
  #       continue-on-error: true
  #       env:
  #         SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}   
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: snyk/actions/setup@master
    - uses: actions/setup-go@v1
      continue-on-error: true
      with:
        go-version: "1.13"
    - name: Snyk test
      run: snyk test
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          
  BotCheck:
    permissions: write-all
    runs-on: ubuntu-latest
    needs: [ Snyk_scanning, TruffleHog_scanning ]
    steps:
      - uses: Vigneshkna/pr-scan-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
